import Image from "next/image";
import Link from "next/link";

const LOGO = "/branding/alttez-symbol-transparent.png";

function BrandPanel() {
  return <aside className="auth-shell__brand"><div className="auth-shell__brand-grid" aria-hidden="true" /><Link className="auth-shell__logo" href="/" aria-label="ALTTEZ Torneos, volver al inicio"><Image src={LOGO} alt="" width={26} height={26} /><span>ALTTEZ Torneos</span></Link><div className="auth-shell__statement"><p>Acceso seguro para organizadores</p><h2>Tu torneo, bajo control.</h2><div className="auth-shell__systems"><span>Competencias</span><span>Programación</span><span>Portal público</span></div></div><div className="auth-shell__foot"><span>Operación competitiva deportiva</span><span>© {new Date().getFullYear()} ALTTEZ S.A.S.</span></div></aside>;
}

export default function AuthShell({ children, maxWidth = 440 }) {
  return <div className="alttez-auth-root light"><BrandPanel /><main className="auth-shell__main"><div className="auth-shell__mobile-brand"><Image src={LOGO} alt="" width={26} height={26} /><strong>ALTTEZ</strong></div><div className="auth-shell__content" style={{ maxWidth }}>{children}</div></main><style>{`
    .alttez-auth-root{min-height:100dvh;display:grid;grid-template-columns:minmax(360px,42%) 1fr;background:#EEECE7;color:#111315;font-family:var(--font-inter),sans-serif}.alttez-auth-root *{box-sizing:border-box}.auth-shell__brand{position:relative;min-height:100dvh;padding:42px clamp(32px,4vw,64px);overflow:hidden;background:#111315;color:#F5F7F8;display:flex;flex-direction:column;justify-content:space-between}.auth-shell__brand-grid{position:absolute;inset:0;pointer-events:none;background-image:linear-gradient(rgba(245,247,248,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(245,247,248,.04) 1px,transparent 1px);background-size:64px 64px;mask-image:linear-gradient(145deg,black,transparent 72%)}
    .auth-shell__logo{position:relative;display:flex;align-items:center;gap:12px;color:#F5F7F8;text-decoration:none;font:750 16px/1 var(--font-sora),sans-serif;letter-spacing:.08em}.auth-shell__logo img,.auth-shell__mobile-brand img{width:26px;height:26px;object-fit:contain;filter:brightness(0) invert(1)}.auth-shell__statement{position:relative;max-width:560px}.auth-shell__statement>p{margin:0 0 24px;color:#C27A42;font-size:11px;font-weight:650;letter-spacing:.12em;text-transform:uppercase}.auth-shell__statement h2{max-width:520px;margin:0;font:650 clamp(40px,4.8vw,72px)/.98 var(--font-sora),sans-serif;letter-spacing:-.055em;text-wrap:balance}.auth-shell__systems{display:flex;flex-wrap:wrap;gap:8px 22px;margin-top:38px;padding-top:22px;border-top:1px solid #303438;color:#8E959B;font-size:11px}.auth-shell__systems span:before{content:"";display:inline-block;width:5px;height:5px;margin-right:8px;border-radius:50%;background:#C27A42;vertical-align:1px}.auth-shell__foot{position:relative;display:flex;justify-content:space-between;gap:20px;color:#666D72;font-size:9px;letter-spacing:.04em}
    .auth-shell__main{position:relative;min-width:0;display:flex;align-items:center;justify-content:center;padding:56px clamp(24px,7vw,112px)}.auth-shell__content{width:100%}.auth-shell__mobile-brand{display:none;align-items:center;gap:10px;margin-bottom:56px;font:750 14px/1 var(--font-sora),sans-serif;letter-spacing:.07em}.auth-shell__mobile-brand img{filter:none}.alttez-auth-root input:-webkit-autofill{-webkit-box-shadow:0 0 0 1000px #F8F7F3 inset!important;-webkit-text-fill-color:#111315!important}.alttez-auth-root input:focus{border-color:#C27A42!important;box-shadow:0 0 0 3px rgba(194,122,66,.14)!important}.alttez-auth-root button:focus-visible,.alttez-auth-root a:focus-visible{outline:3px solid rgba(194,122,66,.4);outline-offset:3px}
    @media(max-width:880px){.alttez-auth-root{display:block}.auth-shell__brand{display:none}.auth-shell__main{min-height:100dvh;display:block;padding:32px 24px 56px}.auth-shell__mobile-brand{display:flex}.auth-shell__content{margin:0 auto}}@media(prefers-reduced-motion:reduce){.alttez-auth-root *{transition-duration:.01ms!important}}
  `}</style></div>;
}
