import { ALERT_SEVERITY } from "./alertSeverity";
import { CATEGORY_STATES } from "./categoryStates";

export const CATEGORY_PRIMARY_STATE_PRIORITY = Object.freeze([
  CATEGORY_STATES.HAS_INCIDENTS,
  CATEGORY_STATES.COMPETITION_ACTIVE,
  CATEGORY_STATES.NEEDS_GROUP_DRAW,
  CATEGORY_STATES.OPEN_REGISTRATION,
  CATEGORY_STATES.PAUSED,
  CATEGORY_STATES.COMPLETED,
]);

export const ALERT_SEVERITY_PRIORITY = Object.freeze({
  [ALERT_SEVERITY.CRITICAL]: 0,
  [ALERT_SEVERITY.HIGH]: 1,
  [ALERT_SEVERITY.MEDIUM]: 2,
  [ALERT_SEVERITY.LOW]: 3,
});
